name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python Wheel
      run: pip install wheel
    - name: Install PlatformIO Core
      run: pip install -U platformio
    - name: Copy generic config over
      run: cp config.Labox.h config.h
    - name: Compile Command Station Labox (ESP32)
      run: python -m platformio run
